### PR TITLE
Fix race, update API and container image

### PR DESCRIPTION
**Pull request by r10r**
* Fix race in `lxcri start`
* Make go-lxc config item wrapper functions private
* Upgrade container image

### CODE REVIEW

**Comment by r10r** [comment]
Hi @stgraber I need your help on the pull request checks. The 'Branch target' and 'DCO' checks are always stuck. 
I know what the DCO check does - but what is the 'Branch target' action check all about?

**Comment by stgraber** [comment]
The tests are currently waiting as we need to restart jenkins for a security update, they'll be scheduled right after that.
The DCO check confirms all commits have the Signed-off-by string, the branch target check validates that code is targeted at the main branch.

**Comment by r10r** [comment]
> The tests are currently waiting as we need to restart jenkins for a security update, they'll be scheduled right after that.

Thanks for the info! I was too fast with merging. Next time I'll wait for the checks to complete.

**Comment by r10r** [comment]
Can we implemented these checks through github actions in the long run ?

**Comment by stgraber** [comment]
Github would need to improve for that. There isn't a way currently to add Github Actions to all projects within an organization without having to manually commit them to every repos.

**Comment by r10r** [comment]
Ok, I see!

**Pull request merged**
